//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.isecurity {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:8080/isecurity", ConfigurationName="isecurity.ISecurity")]
    public interface ISecurity {
        
        // CODEGEN: Контракт генерации сообщений с операцией GetPolicy не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfApp2.isecurity.GetPolicyResponse1 GetPolicy(WpfApp2.isecurity.GetPolicyRequest1 request);
        
        // CODEGEN: Контракт генерации сообщений с операцией GetUserDetails не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfApp2.isecurity.GetUserDetailsResponse1 GetUserDetails(WpfApp2.isecurity.GetUserDetailsRequest1 request);
        
        // CODEGEN: Контракт генерации сообщений с операцией Login не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfApp2.isecurity.LoginResponse1 Login(WpfApp2.isecurity.LoginRequest1 request);
        
        // CODEGEN: Контракт генерации сообщений с операцией GetComputerDetails не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfApp2.isecurity.GetComputerDetailsResponse1 GetComputerDetails(WpfApp2.isecurity.GetComputerDetailsRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://localhost:8080/isecurity")]
    public partial class GetPolicyRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sessionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string session {
            get {
                return this.sessionField;
            }
            set {
                this.sessionField = value;
                this.RaisePropertyChanged("session");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:8080/isecurity")]
    public partial class ComputerDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string ipField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ip {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
                this.RaisePropertyChanged("ip");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:8080/isecurity")]
    public partial class UserDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("firstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("lastName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:8080/isecurity")]
    public partial class policy : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string nameField;
        
        private string[] bannedAppsField;
        
        private string[] bannedSitesField;
        
        private string[] loginMethodsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("bannedApps", Order=2)]
        public string[] bannedApps {
            get {
                return this.bannedAppsField;
            }
            set {
                this.bannedAppsField = value;
                this.RaisePropertyChanged("bannedApps");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("bannedSites", Order=3)]
        public string[] bannedSites {
            get {
                return this.bannedSitesField;
            }
            set {
                this.bannedSitesField = value;
                this.RaisePropertyChanged("bannedSites");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("loginMethods", Order=4)]
        public string[] loginMethods {
            get {
                return this.loginMethodsField;
            }
            set {
                this.loginMethodsField = value;
                this.RaisePropertyChanged("loginMethods");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://localhost:8080/isecurity")]
    public partial class GetPolicyResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private policy policyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public policy policy {
            get {
                return this.policyField;
            }
            set {
                this.policyField = value;
                this.RaisePropertyChanged("policy");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPolicyRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost:8080/isecurity", Order=0)]
        public WpfApp2.isecurity.GetPolicyRequest GetPolicyRequest;
        
        public GetPolicyRequest1() {
        }
        
        public GetPolicyRequest1(WpfApp2.isecurity.GetPolicyRequest GetPolicyRequest) {
            this.GetPolicyRequest = GetPolicyRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPolicyResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost:8080/isecurity", Order=0)]
        public WpfApp2.isecurity.GetPolicyResponse GetPolicyResponse;
        
        public GetPolicyResponse1() {
        }
        
        public GetPolicyResponse1(WpfApp2.isecurity.GetPolicyResponse GetPolicyResponse) {
            this.GetPolicyResponse = GetPolicyResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://localhost:8080/isecurity")]
    public partial class GetUserDetailsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sessionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string session {
            get {
                return this.sessionField;
            }
            set {
                this.sessionField = value;
                this.RaisePropertyChanged("session");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://localhost:8080/isecurity")]
    public partial class GetUserDetailsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private UserDetails userDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public UserDetails UserDetails {
            get {
                return this.userDetailsField;
            }
            set {
                this.userDetailsField = value;
                this.RaisePropertyChanged("UserDetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserDetailsRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost:8080/isecurity", Order=0)]
        public WpfApp2.isecurity.GetUserDetailsRequest GetUserDetailsRequest;
        
        public GetUserDetailsRequest1() {
        }
        
        public GetUserDetailsRequest1(WpfApp2.isecurity.GetUserDetailsRequest GetUserDetailsRequest) {
            this.GetUserDetailsRequest = GetUserDetailsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserDetailsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost:8080/isecurity", Order=0)]
        public WpfApp2.isecurity.GetUserDetailsResponse GetUserDetailsResponse;
        
        public GetUserDetailsResponse1() {
        }
        
        public GetUserDetailsResponse1(WpfApp2.isecurity.GetUserDetailsResponse GetUserDetailsResponse) {
            this.GetUserDetailsResponse = GetUserDetailsResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://localhost:8080/isecurity")]
    public partial class LoginRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string loginField;
        
        private string passwordField;
        
        private long computerIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long computerId {
            get {
                return this.computerIdField;
            }
            set {
                this.computerIdField = value;
                this.RaisePropertyChanged("computerId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://localhost:8080/isecurity")]
    public partial class LoginResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sessionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string session {
            get {
                return this.sessionField;
            }
            set {
                this.sessionField = value;
                this.RaisePropertyChanged("session");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost:8080/isecurity", Order=0)]
        public WpfApp2.isecurity.LoginRequest LoginRequest;
        
        public LoginRequest1() {
        }
        
        public LoginRequest1(WpfApp2.isecurity.LoginRequest LoginRequest) {
            this.LoginRequest = LoginRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost:8080/isecurity", Order=0)]
        public WpfApp2.isecurity.LoginResponse LoginResponse;
        
        public LoginResponse1() {
        }
        
        public LoginResponse1(WpfApp2.isecurity.LoginResponse LoginResponse) {
            this.LoginResponse = LoginResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://localhost:8080/isecurity")]
    public partial class GetComputerDetailsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sessionField;
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string session {
            get {
                return this.sessionField;
            }
            set {
                this.sessionField = value;
                this.RaisePropertyChanged("session");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://localhost:8080/isecurity")]
    public partial class GetComputerDetailsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ComputerDetails computerDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ComputerDetails ComputerDetails {
            get {
                return this.computerDetailsField;
            }
            set {
                this.computerDetailsField = value;
                this.RaisePropertyChanged("ComputerDetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetComputerDetailsRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost:8080/isecurity", Order=0)]
        public WpfApp2.isecurity.GetComputerDetailsRequest GetComputerDetailsRequest;
        
        public GetComputerDetailsRequest1() {
        }
        
        public GetComputerDetailsRequest1(WpfApp2.isecurity.GetComputerDetailsRequest GetComputerDetailsRequest) {
            this.GetComputerDetailsRequest = GetComputerDetailsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetComputerDetailsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost:8080/isecurity", Order=0)]
        public WpfApp2.isecurity.GetComputerDetailsResponse GetComputerDetailsResponse;
        
        public GetComputerDetailsResponse1() {
        }
        
        public GetComputerDetailsResponse1(WpfApp2.isecurity.GetComputerDetailsResponse GetComputerDetailsResponse) {
            this.GetComputerDetailsResponse = GetComputerDetailsResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISecurityChannel : WpfApp2.isecurity.ISecurity, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecurityClient : System.ServiceModel.ClientBase<WpfApp2.isecurity.ISecurity>, WpfApp2.isecurity.ISecurity {
        
        public SecurityClient() {
        }
        
        public SecurityClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecurityClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApp2.isecurity.GetPolicyResponse1 WpfApp2.isecurity.ISecurity.GetPolicy(WpfApp2.isecurity.GetPolicyRequest1 request) {
            return base.Channel.GetPolicy(request);
        }
        
        public WpfApp2.isecurity.GetPolicyResponse GetPolicy(WpfApp2.isecurity.GetPolicyRequest GetPolicyRequest) {
            WpfApp2.isecurity.GetPolicyRequest1 inValue = new WpfApp2.isecurity.GetPolicyRequest1();
            inValue.GetPolicyRequest = GetPolicyRequest;
            WpfApp2.isecurity.GetPolicyResponse1 retVal = ((WpfApp2.isecurity.ISecurity)(this)).GetPolicy(inValue);
            return retVal.GetPolicyResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApp2.isecurity.GetUserDetailsResponse1 WpfApp2.isecurity.ISecurity.GetUserDetails(WpfApp2.isecurity.GetUserDetailsRequest1 request) {
            return base.Channel.GetUserDetails(request);
        }
        
        public WpfApp2.isecurity.GetUserDetailsResponse GetUserDetails(WpfApp2.isecurity.GetUserDetailsRequest GetUserDetailsRequest) {
            WpfApp2.isecurity.GetUserDetailsRequest1 inValue = new WpfApp2.isecurity.GetUserDetailsRequest1();
            inValue.GetUserDetailsRequest = GetUserDetailsRequest;
            WpfApp2.isecurity.GetUserDetailsResponse1 retVal = ((WpfApp2.isecurity.ISecurity)(this)).GetUserDetails(inValue);
            return retVal.GetUserDetailsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApp2.isecurity.LoginResponse1 WpfApp2.isecurity.ISecurity.Login(WpfApp2.isecurity.LoginRequest1 request) {
            return base.Channel.Login(request);
        }
        
        public WpfApp2.isecurity.LoginResponse Login(WpfApp2.isecurity.LoginRequest LoginRequest) {
            WpfApp2.isecurity.LoginRequest1 inValue = new WpfApp2.isecurity.LoginRequest1();
            inValue.LoginRequest = LoginRequest;
            WpfApp2.isecurity.LoginResponse1 retVal = ((WpfApp2.isecurity.ISecurity)(this)).Login(inValue);
            return retVal.LoginResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApp2.isecurity.GetComputerDetailsResponse1 WpfApp2.isecurity.ISecurity.GetComputerDetails(WpfApp2.isecurity.GetComputerDetailsRequest1 request) {
            return base.Channel.GetComputerDetails(request);
        }
        
        public WpfApp2.isecurity.GetComputerDetailsResponse GetComputerDetails(WpfApp2.isecurity.GetComputerDetailsRequest GetComputerDetailsRequest) {
            WpfApp2.isecurity.GetComputerDetailsRequest1 inValue = new WpfApp2.isecurity.GetComputerDetailsRequest1();
            inValue.GetComputerDetailsRequest = GetComputerDetailsRequest;
            WpfApp2.isecurity.GetComputerDetailsResponse1 retVal = ((WpfApp2.isecurity.ISecurity)(this)).GetComputerDetails(inValue);
            return retVal.GetComputerDetailsResponse;
        }
    }
}
