//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.user {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:8080/user", ConfigurationName="user.UserPort")]
    public interface UserPort {
        
        // CODEGEN: Контракт генерации сообщений с операцией GetUserDetails не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfApp2.user.GetUserDetailsResponse1 GetUserDetails(WpfApp2.user.GetUserDetailsRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://localhost:8080/user")]
    public partial class GetUserDetailsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sessionField;
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string session {
            get {
                return this.sessionField;
            }
            set {
                this.sessionField = value;
                this.RaisePropertyChanged("session");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:8080/user")]
    public partial class UserDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("firstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("lastName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://localhost:8080/user")]
    public partial class GetUserDetailsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private UserDetails userDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public UserDetails UserDetails {
            get {
                return this.userDetailsField;
            }
            set {
                this.userDetailsField = value;
                this.RaisePropertyChanged("UserDetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserDetailsRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost:8080/user", Order=0)]
        public WpfApp2.user.GetUserDetailsRequest GetUserDetailsRequest;
        
        public GetUserDetailsRequest1() {
        }
        
        public GetUserDetailsRequest1(WpfApp2.user.GetUserDetailsRequest GetUserDetailsRequest) {
            this.GetUserDetailsRequest = GetUserDetailsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserDetailsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost:8080/user", Order=0)]
        public WpfApp2.user.GetUserDetailsResponse GetUserDetailsResponse;
        
        public GetUserDetailsResponse1() {
        }
        
        public GetUserDetailsResponse1(WpfApp2.user.GetUserDetailsResponse GetUserDetailsResponse) {
            this.GetUserDetailsResponse = GetUserDetailsResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserPortChannel : WpfApp2.user.UserPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserPortClient : System.ServiceModel.ClientBase<WpfApp2.user.UserPort>, WpfApp2.user.UserPort {
        
        public UserPortClient() {
        }
        
        public UserPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApp2.user.GetUserDetailsResponse1 WpfApp2.user.UserPort.GetUserDetails(WpfApp2.user.GetUserDetailsRequest1 request) {
            return base.Channel.GetUserDetails(request);
        }
        
        public WpfApp2.user.GetUserDetailsResponse GetUserDetails(WpfApp2.user.GetUserDetailsRequest GetUserDetailsRequest) {
            WpfApp2.user.GetUserDetailsRequest1 inValue = new WpfApp2.user.GetUserDetailsRequest1();
            inValue.GetUserDetailsRequest = GetUserDetailsRequest;
            WpfApp2.user.GetUserDetailsResponse1 retVal = ((WpfApp2.user.UserPort)(this)).GetUserDetails(inValue);
            return retVal.GetUserDetailsResponse;
        }
    }
}
